networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "/etc/letsencrypt:/etc/letsencrypt"
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./backend
    networks:
      - dev
    network_mode: host
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://admin:dudHjgDhe73!@localhost:5432/bookings

  frontend:
    build:
      context: ./frontend
    networks:
      - dev
