networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "/etc/letsencrypt:/etc/letsencrypt"
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./backend
    network_mode: "host"
    environment:
      - DATABASE_URL=postgresql://admin:dudHjgDhe73!@localhost:5432/bookings
    command: >
      uvicorn main:app
        --host 0.0.0.0
        --port 8000
  frontend:
    build:
      context: ./frontend
    networks:
      - dev
