version: "3.8"

services:
  backend:
    build:
      context: ./backend
    extra_hosts:
      # Docker 20.10+ автоподставит IP хоста под этим именем
      - "host.docker.internal:host-gateway"
    environment:
      # Экранируем '!' как %21
      - DATABASE_URL=postgresql://admin:dudHjgDhe73%21@host.docker.internal:5432/bookings
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    networks:
      - dev

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend
    networks:
      - dev

networks:
  dev:
